// <auto-generated />
namespace Repositorio.DALL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablecep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablecep));
        
        string IMigrationMetadata.Id
        {
            get { return "201707212021296_table-cep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
