// <auto-generated />
namespace Repositorio.DALL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REFATORAÇÃOMODELA22A23A24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REFATORAÇÃOMODELA22A23A24));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111937374_REFATORAÇÃO-MODEL-A22-A23-A24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
